
$.ajax({
    url: '/user/profile/save',
    method: 'POST',
    data: {
        nickname: "我是管理员",
        firstname: "管",
        midname: "理",
        lastname: "员",
        language: "汉语+英语",
        jobtitle: "管理工作",
        title: "超级管理员",
        birthday: "2019-08-14",
        department: "管理员部门",
        gender: "男",
        name: "管理员",
        email: "admin@5704.com",
        mobile: "18500000000",
        phone: "18500000000",
        parent_phone: "18500000000",
        organ: "管理员组织部门",
        skill: "管理5704系统",
        city: "成都",
        province: "四川省",
        user_id: "201913160711",
        grade: "2019",
        major: "计算机类",
        room_id: "松林1#319",
        join_time: "2019-09-09",
        sign: "管理员的签名就是不一样",
        description: "管理员不需要描述",
        remark: "也不需要备注",
        username: "admin",
        secureconf: "5",
        usertype: "0",
        creater: "Davies",
        integral: "134",
        status: "正常",
        rank: "核心成员",
    },
    success: function (data) {
        console.log(data);
    }
});